/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.Controller.HoaDonChiTietController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class formHoaDon extends javax.swing.JPanel {
    private HoaDonChiTietController controller;
    /**
     * Creates new form formHoaDon
     * @param userId
     */
    public formHoaDon(Integer userId) {
        initComponents();
        table.setModel(new DefaultTableModel(new Object[][] {}, new String[] {"ID", "Product name", "Price", "Quantity"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                    return false;
            }
        });
        scrollPane.setViewportView(table);
        controller = new HoaDonChiTietController(userId, txfPrice, txfPrice, txfQuantity, txfPrice, txfPhone, txfAddress, txfTotal, table, cbCus, cbPro, btnAdd, btnCancel, btnPay, btnDel);
    }
    
    public HoaDonChiTietController getController() {
        return controller;
    }

    public void setController(HoaDonChiTietController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfPhone = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txfPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txfQuantity = new javax.swing.JTextField();
        cbPro = new javax.swing.JComboBox<>();
        txfAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCus = new javax.swing.JComboBox<>();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txfTotal = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText(" BILL DETAIL");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jLabel1.setText("BILL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 215, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Customer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setText("Phone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));
        jPanel1.add(txfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        btnAdd.setText("Add");
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 80, -1));

        jLabel9.setText("Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel1.add(txfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 390, -1));

        jLabel12.setText("Quantity");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        jPanel1.add(txfQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 300, -1));

        cbPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 390, -1));
        jPanel1.add(txfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 190, -1));

        jLabel5.setText("Product");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        cbCus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 390, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 630, 230));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(table);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 630, 220));

        jLabel2.setText("Total");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));
        add(txfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 263, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 80, -1));

        btnPay.setText("Pay");
        add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 80, -1));

        btnDel.setText("Delete");
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cbCus;
    private javax.swing.JComboBox<String> cbPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private javax.swing.JTextField txfAddress;
    private javax.swing.JTextField txfPhone;
    private javax.swing.JTextField txfPrice;
    private javax.swing.JTextField txfQuantity;
    private javax.swing.JTextField txfTotal;
    // End of variables declaration//GEN-END:variables
}
