/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import GUI.Controller.LoginController;
/**
 *
 * @author PC
 */
public class formDangNhap extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form formLogin1
     */
    public formDangNhap() {
        initComponents();
        group = new ButtonGroup();
        group.add(rdbtnManage);
        group.add(rdbtnEmployee);
        this.setSize(400, 400);
        login();
    }
    
    private void login() {
        LoginController controll = new LoginController(this, txfUsername, passwordField, rdbtnEmployee, rdbtnManage, btnLogIn);	
       
//        JLabel bg = new JLabel();
//        bg.setBounds(356, 344, 384, 361);
//        mainPanel.add(bg);
//        ImageIcon bgload = new ImageIcon(new ImageIcon(this.getClass().getResource("/background.jpg")).getImage()
//                        .getScaledInstance(bg.getWidth(), bg.getHeight(), Image.SCALE_SMOOTH));
//        bg.setIcon(bgload);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        rdbtnManage = new javax.swing.JRadioButton();
        rdbtnEmployee = new javax.swing.JRadioButton();
        lbPhone = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        lblBrand = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbtnManage.setForeground(new java.awt.Color(25, 25, 112));
        rdbtnManage.setSelected(true);
        rdbtnManage.setText("Manager");
        rdbtnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnManageActionPerformed(evt);
            }
        });
        mainPanel.add(rdbtnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 84, 98, -1));

        rdbtnEmployee.setForeground(new java.awt.Color(25, 25, 112));
        rdbtnEmployee.setText("Employee");
        mainPanel.add(rdbtnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 84, 98, -1));

        lbPhone.setText("Phone");
        mainPanel.add(lbPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 126, 37, -1));

        lblPw.setText("Password");
        mainPanel.add(lblPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 174, 60, -1));
        mainPanel.add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 123, 260, -1));

        btnLogIn.setText("Đăng nhập");
        mainPanel.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        lblBrand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBrand.setText("MOBLE SHOP");
        mainPanel.add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 31, -1, -1));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        mainPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 171, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnManageActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new formDangNhap().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblPw;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JRadioButton rdbtnEmployee;
    private javax.swing.JRadioButton rdbtnManage;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
