/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI;

import GUI.Controller.ThongKeController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class formThongKe extends javax.swing.JPanel {
    private ThongKeController controller;
    /** Creates new form formThongKe */
    public formThongKe() {
        initComponents();
        table.setModel(new DefaultTableModel(new Object[][] {}, new String[] {}));
        scrollStatis.setViewportView(table);
        table_1.setModel(new DefaultTableModel(new Object[][] {}, new String[] {}));
	scrollStatisDate.setViewportView(table_1);
        controller = new ThongKeController(table, table_1, btnPrint, btnCreate, btnCreateByTime, btnPrintByTime, cbReportType, cbYear, beginDate, endDate);
    }
    
    public ThongKeController getController() {
	return controller;
    }

    public void setController(ThongKeController controller) {
         this.controller = controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        scrollStatis = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbReportType = new javax.swing.JComboBox<>();
        cbYear = new com.toedter.calendar.JYearChooser();
        btnCreate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        beginDate = new com.toedter.calendar.JDateChooser();
        endDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnCreateByTime = new javax.swing.JButton();
        btnPrintByTime = new javax.swing.JButton();
        scrollStatisDate = new javax.swing.JScrollPane();
        table_1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("STATISTIC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 215, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollStatis.setViewportView(table);

        jPanel1.add(scrollStatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 600, 120));

        jLabel2.setText("Statistic for revenue by");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 90, -1));
        jPanel1.add(cbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, -1));

        btnCreate.setText("Create");
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        btnPrint.setText("Print");
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 630, 200));

        jPanel2.setBackground(new java.awt.Color(204, 215, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Revenue statistic from");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));
        jPanel2.add(beginDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 160, -1));
        jPanel2.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 150, -1));

        jLabel4.setText("to");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        btnCreateByTime.setText("Create");
        jPanel2.add(btnCreateByTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        btnPrintByTime.setText("Print");
        jPanel2.add(btnPrintByTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollStatisDate.setViewportView(table_1);

        jPanel2.add(scrollStatisDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 610, 170));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 630, 290));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser beginDate;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateByTime;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnPrintByTime;
    private javax.swing.JComboBox<String> cbReportType;
    private com.toedter.calendar.JYearChooser cbYear;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrollStatis;
    private javax.swing.JScrollPane scrollStatisDate;
    private javax.swing.JTable table;
    private javax.swing.JTable table_1;
    // End of variables declaration//GEN-END:variables

}
