/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.stdManage.Views.Student;

import com.stdManage.Dao.AccountDao;
import com.stdManage.Dao.ClassDao;
import com.stdManage.Dao.ClassGroupDao;
import com.stdManage.Dao.CourseDao;
import com.stdManage.Dao.GradeDetailDao;
import com.stdManage.Main.Main;
import com.stdManage.Models.Account;
import com.stdManage.Models.ClassModels;
import com.stdManage.Models.ClassGroup;
import com.stdManage.Models.Course;
import com.stdManage.Models.GradeDetail;
import com.stdManage.Utils.U_Common;
import com.stdManage.Utils.U_ColumnTitles;
import com.stdManage.Utils.U_HelperDao;
import com.stdManage.Utils.U_Styles;
import com.stdManage.Views.Components.Combobox;
import com.stdManage.Views.Components.Dialog.Message;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.stdManage.Views.Swing.JTable.ITableActionEvent;
import com.stdManage.Views.Swing.Table.Table;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author ADMIN
 */
public class F_GroupManager extends javax.swing.JPanel {

    AccountDao accDao = new AccountDao();
    CourseDao courseDao = new CourseDao();
    ClassDao classDao = new ClassDao();
    ClassGroupDao groupDao = new ClassGroupDao();
    GradeDetailDao gradeDao = new GradeDetailDao();
    U_HelperDao helpDao = new U_HelperDao();

    String currentCourse = "-1";
    String currentClass = "-1";
    String currentGroup = "-1";

    /**
     * Creates new form F_GroupManager
     */
    public F_GroupManager() {
        initComponents();
        //init cbb
        initCourseCbb();
    }

    private void loadTableData() {
        tbl_GroupDetails1.initTable(U_ColumnTitles.GRADLE_DETAILS, gradeDao.findAllbyGroup(currentGroup));
        handleTableAction();
    }

    private void loadStudentTable() {
        loadTableData();
        tbl_GroupDetails1.hideColumnAt(new int[]{6, 7});
    }

    private void initGroupCbb() {
        List<Object[]> list = helpDao.covertToListObject1D(groupDao.findAllbyCourse(currentClass));
        cbb_groupClass.init(list.toArray(), 0, "Group", 1);
    }

    private void initClassCbb() {
        List<Object[]> list = helpDao.covertToListObject1D(classDao.findAllbyCourse(currentCourse));
        cbb_class.init(list.toArray(), 0, "Class", 1);
    }

    private void initCourseCbb() {
        List<Object[]> list = courseDao.convertToListObject1D(courseDao.findAll());
        cbb_course.init(list.toArray(), 0, "Course", 1);
    }

    private void handleTableAction() {
        ITableActionEvent event = new ITableActionEvent() {
            @Override
            public void onFirstButton(int row, int col) {
                System.out.println("Edit row : " + row);
            }

            @Override
            public void onSecondButton(int row, int col) {
                if (tbl_GroupDetails1.isEditing()) {
                    tbl_GroupDetails1.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel) tbl_GroupDetails1.getModel();
                model.removeRow(row);
            }

        };
        tbl_GroupDetails1.createActionColumn(event, U_Common.ActionTable.ADD);
    }

    private String getCbbObjectAt(Combobox cbb, int idxValue) {
        int idxSelected = cbb.getSelectedIndex();
        if (idxSelected >= 0) {
            Object[] value = (Object[]) cbb.getSelectedItem();
            return value[idxValue].toString();
        }
        return null;
    }

    private boolean showMessage(String message) {
        Message obj = new Message(Main.getFrames()[0], true);
        obj.showMessage(message);
        return obj.isOk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GroupDetails1 = new com.stdManage.Views.Swing.Table.Table();
        jPanel1 = new javax.swing.JPanel();
        cbb_course = new com.stdManage.Views.Components.Combobox();
        textField1 = new com.stdManage.Views.Components.TextField();
        cbb_class = new com.stdManage.Views.Components.Combobox();
        cbb_groupClass = new com.stdManage.Views.Components.Combobox();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new com.stdManage.Views.Swing.Table.Table();

        setPreferredSize(new java.awt.Dimension(1058, 741));

        tbl_GroupDetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_GroupDetails1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbb_course.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_courseItemStateChanged(evt);
            }
        });

        textField1.setLabelText("Course");

        cbb_class.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_classItemStateChanged(evt);
            }
        });

        cbb_groupClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_groupClassItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cbb_course, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cbb_class, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(cbb_groupClass, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_groupClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbb_courseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_courseItemStateChanged
        currentCourse = getCbbObjectAt(cbb_course, 0);
        initClassCbb();
    }//GEN-LAST:event_cbb_courseItemStateChanged

    private void cbb_classItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_classItemStateChanged
        currentClass = getCbbObjectAt(cbb_class, 0);
        initGroupCbb();
    }//GEN-LAST:event_cbb_classItemStateChanged

    private void cbb_groupClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_groupClassItemStateChanged
        currentGroup = getCbbObjectAt(cbb_groupClass, 0);
        loadStudentTable();
    }//GEN-LAST:event_cbb_groupClassItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.stdManage.Views.Components.Combobox cbb_class;
    private com.stdManage.Views.Components.Combobox cbb_course;
    private com.stdManage.Views.Components.Combobox cbb_groupClass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.stdManage.Views.Swing.Table.Table table1;
    private com.stdManage.Views.Swing.Table.Table tbl_GroupDetails1;
    private com.stdManage.Views.Components.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
